/**
 * [BoxLang]
 *
 * Copyright [2023] [Ortus Solutions, Corp]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ortus.boxlang.modules.orm.hibernate.facade;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * The classloader that holds one ORM application build's generated entity facades.
 * <p>
 * Every {@code ORMApp} startup (first boot and every reload) gets a fresh instance whose parent is the ORM module
 * classloader. A facade's fully-qualified name is stable per application and entity, and a JVM classloader can only
 * define a given name once, so giving each build its own loader is what lets a reload define <em>new</em> facade classes
 * when an entity changes (a new property, a changed association) instead of reusing the previous build's class. When the
 * old application shuts down its session factories, nothing references the old loader any more and its facades can be
 * garbage collected.
 * <p>
 * In {@code trust} manifest mode the loader also carries the pre-generated facade bytecode read from
 * {@code .bxorm/facades.jar}, scoped to this build only (never shared JVM-wide), so a later non-trust build can never
 * pick up stale jar bytecode.
 */
public final class FacadeClassLoader extends ClassLoader {

	static {
		registerAsParallelCapable();
	}

	/** Facade classes generated (or injected) into this loader, keyed by fully-qualified name. */
	private final Map<String, Class<?>>	facades			= new ConcurrentHashMap<>();

	/** Pre-generated facade bytecode for this build (trust mode), keyed by fully-qualified name. */
	private final Map<String, byte[]>	pregenerated;

	/** How many facades were defined from pre-generated bytecode rather than generated with ByteBuddy. */
	private final AtomicInteger			definedFromJar	= new AtomicInteger();

	/**
	 * Create a facade loader with no pre-generated bytecode.
	 *
	 * @param parent The ORM module classloader (resolves the module's own classes the facades reference).
	 */
	public FacadeClassLoader( ClassLoader parent ) {
		this( parent, Map.of() );
	}

	/**
	 * Create a facade loader carrying pre-generated facade bytecode (trust mode).
	 *
	 * @param parent       The ORM module classloader.
	 * @param pregenerated Facade bytecode read from {@code facades.jar} (FQN to class bytes); may be empty.
	 */
	public FacadeClassLoader( ClassLoader parent, Map<String, byte[]> pregenerated ) {
		super( "bx-orm-facades", parent );
		this.pregenerated = pregenerated == null ? Map.of() : Map.copyOf( pregenerated );
	}

	/**
	 * The facade classes generated into this loader, keyed by fully-qualified name.
	 *
	 * @return The live facade cache for this build.
	 */
	Map<String, Class<?>> facades() {
		return this.facades;
	}

	/**
	 * The pre-generated bytecode for a facade, if this build was given any.
	 *
	 * @param className The facade's fully-qualified name.
	 *
	 * @return The class bytes, or {@code null} if there are none.
	 */
	byte[] pregenerated( String className ) {
		return this.pregenerated.get( className );
	}

	/**
	 * Define a facade from pre-generated bytecode.
	 *
	 * @param className The facade's fully-qualified name.
	 * @param bytes     The class bytes.
	 *
	 * @return The defined class.
	 */
	Class<?> defineFromBytes( String className, byte[] bytes ) {
		Class<?> defined = defineClass( className, bytes, 0, bytes.length );
		this.definedFromJar.incrementAndGet();
		return defined;
	}

	/**
	 * How many facades this build defined from pre-generated ({@code facades.jar}) bytecode instead of generating them.
	 *
	 * @return The count of jar-defined facades.
	 */
	public int getDefinedFromJarCount() {
		return this.definedFromJar.get();
	}

	/**
	 * How many facade classes this build holds.
	 *
	 * @return The number of facades generated or defined in this loader.
	 */
	public int getFacadeCount() {
		return this.facades.size();
	}
}
